[package]
name = "yt-downloader"
version = "0.1.0"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = {version = "2.33.0", features = ["yaml", "wrap_help"]}
serde = { version = "1.0.104", features = ["derive"] }
regex = "1.3.1"
lazy_static = "1.4.0"
