[package]
name = "yt-downloader"
version = "0.1.0"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = {version = "2.33.0", features = ["yaml", "wrap_help"]}
serde = { version = "1.0.104", features = ["derive"] }
regex = "1.3.1"
lazy_static = "1.4.0"
indicatif = "0.13.0"
colored = "1.9.1"
semver = "0.9.0"
log = "0.4.8"
env_logger = "0.7.1"
serde_json = "1.0.44"
chrono = "0.4.10"
