[package]
name = "yt-downloader"
version = "0.2.0"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
clap = { version = "2.33.3", features = ["yaml", "wrap_help"] }
serde = { version = "1.0.126", features = ["derive"] }
regex = "1.5.4"
lazy_static = "1.4.0"
indicatif = "0.16.0"
colored = "2.0.0"
semver = "0.11.0"
log = "0.4.14"
env_logger = "0.8.3"
serde_json = "1.0.64"
chrono = "0.4.19"
fs_extra = "1.2.0"
shellexpand = "2.1.0"
