//! Module for all common Data, like structs & their implementations
pub mod cache;
pub mod old_archive;
pub mod sql_models;
/// SQL Schemas generated by Diesel
pub mod sql_schema;

/// Common type for a unknown field, where nothing was provided
///
/// Example: importing a ytdl archive which is "id provider" only
pub const UNKNOWN_NONE_PROVIDED: &str = "unknown (none-provided)";
