//! Module for all common Data, like structs & their implementations
pub mod json_archive;
pub mod provider;
pub mod sql_models;
/// SQL Schemas generated by Diesel
pub mod sql_schema;
pub mod video;
