[package]
name = "ytdlr"
version = "0.4.0"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "3.1.13", features = ["derive", "wrap_help", "env"] }
lazy_static = "1.4.0"
indicatif = "0.16.2"
colored = "2.0.0"
log = "0.4.16"
flexi_logger = "0.22" # this logger, because "env_logger" and "simple_logger" do not provide setting the log level dynamically
time = "0.3" # to format the time for the logging
atty = "0.2"
diesel = { version = "2.0.0-rc.0", features = ["sqlite", "chrono"] } # TODO: replace with 2.0.0 release
libytdlr = { path = "../libytdlr" }
dirs-next = "2.0.0"

[[bin]]
name = "ytdlr"
path = "src/main.rs"
