[package]
name = "ytdlr"
version = "0.5.0"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2021"
license = "MIT"
build = "build.rs"

[dependencies]
clap = { version = "4.1", features = ["derive", "wrap_help", "env"] }
lazy_static = "1.4.0"
indicatif = "0.17.3"
colored = "2.0.0"
log = "0.4"
flexi_logger = "0.25" # this logger, because "env_logger" and "simple_logger" do not provide setting the log level dynamically
time = "0.3" # to format the time for the logging
atty = "0.2"
diesel = { version = "2.0.2", features = ["sqlite", "chrono"] }
libytdlr = { path = "../libytdlr" }
dirs-next = "2.0.0"
term_size = "0.3"
regex = "1.5"
sysinfo = "0.27"
ctrlc = { version = "3", features = ["termination"] }
once_cell = "1.17"
# the following 2 are required to get the correct boundaries to truncate at
unicode-segmentation = "1.10" # cluster all characters into display-able characters
unicode-width = "0.1" # get display width of a given string

[[bin]]
name = "ytdlr"
path = "src/main.rs"
