[package]
name = "ytdlr"
version = "0.4.0"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "3.0.9", features = ["derive", "wrap_help", "env"] }
lazy_static = "1.4.0"
indicatif = "0.16.2"
colored = "2.0.0"
log = "0.4.14"
env_logger = "0.9.0"
serde_json = "1.0.74"
atty = "0.2"
libytdlr = { path = "../libytdlr" }

[[bin]]
name = "ytdlr"
path = "src/main.rs"
