[package]
name = "libytdlr"
version = "0.4.0"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
regex = "1.5.4"
lazy_static = "1.4.0"
indicatif = "0.16.2" # TODO: remove this from lib
colored = "2.0.0" # TODO: remove this from lib
log = "0.4.14"
serde_json = "1.0.74"
fs_extra = "1.2.0"
dirs-next = "2.0.0"
path-absolutize = "3.0" # Replace with official implementation, RFC: https://github.com/rust-lang/rfcs/issues/2208

[dev-dependencies]
serde_test = "1.0.117"

[lib]
name = "libytdlr"
path = "src/lib.rs"
