[package]
name = "libytdlr"
version = "0.6.0"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
regex = "1.7"
lazy_static = "1.4"
log = "0.4"
serde_json = "1.0"
dirs-next = "2.0"
path-absolutize = "3.0" # Replace with official implementation, RFC: https://github.com/rust-lang/rfcs/issues/2208
diesel = { version = "2.0", features = ["sqlite", "chrono"] }
diesel_migrations = { version = "2.0.0" }
chrono = "0.4"
duct = "0.13" # required to pipe stderr into stdout

[dev-dependencies]
serde_test = "1.0.159"
serial_test = { version = "2.0.0", default-features = false, features = ["logging"] } # disable "async" feature, because not used here
uuid = { version = "1.3", features = ["v4"] }

[lib]
name = "libytdlr"
path = "src/lib.rs"
