[package]
name = "libytdlr"
version = "0.4.0"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
regex = "1.5"
lazy_static = "1.4"
log = "0.4"
serde_json = "1.0.74"
dirs-next = "2.0.0"
path-absolutize = "3.0" # Replace with official implementation, RFC: https://github.com/rust-lang/rfcs/issues/2208
diesel = { git = "https://github.com/diesel-rs/diesel.git", features = ["sqlite", "chrono"] } # TODO: replace with 2.0.0 release
diesel_migrations = { git = "https://github.com/diesel-rs/diesel.git" } # TODO: replace with 2.0.0 release
chrono = "0.4"

[dev-dependencies]
serde_test = "1.0.117"
serial_test = "0.6.0"

[lib]
name = "libytdlr"
path = "src/lib.rs"
